name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  checks: write

env:
  VERSION: 1.0.7

jobs:
  release:
    name: Release and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      # Install Cosign for signing the build
      - name: Install Cosign
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/download/v1.4.1/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      # Sign the package files using cosign
      - name: Sign package files
        run: |
          cosign sign-blob --key <(echo "${{ secrets.COSIGN_KEY }}") package.json
          cosign sign-blob --key <(echo "${{ secrets.COSIGN_KEY }}") package-lock.json
          cosign sign-blob --key <(echo "${{ secrets.COSIGN_KEY }}") README.md
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      # Pull, Commit, and Push Version Bump
      - name: Pull, Commit, and Push
        run: |
          git config --global user.email "amjaradat01@gmail.com"
          git config --global user.name "Ali Jaradat"
          
          # Add any changes to version-controlled files
          git add package.json package-lock.json README.md .github/workflows/release.yml
          
          # Commit changes (if there are any)
          git commit -m "chore: prepare release for ${{ env.VERSION }}" || echo "No changes to commit"
          
          # Pull the latest changes from the remote main branch
          git pull origin main --rebase
          
          # Push the changes to main
          git push origin main
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publish to npm
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Optionally create a GitHub release only if the tag doesn't exist
      - name: Check if Tag Exists
        id: tag_exists
        run: |
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag v${{ env.VERSION }} already exists."
            exit 1
          else
            echo "Tag v${{ env.VERSION }} does not exist."
          fi

      - name: Create GitHub Release (only if tag doesn't exist)
        if: steps.tag_exists.outputs.exitcode != '1'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
